#!/bin/bash
#
# RaspiMonitorMail
#
# Copyright (C) 2012 Daniele Lando <i@danielelando.me>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
#

############ Config Params ############

user="pi"
tempmax="55"
dest="email@address.com"

ip_old="`tail /home/$user/.raspimonitor`"
ip="`wget -qO- http://checkip.dyndns.org/ | sed "s/.* \([[:digit:]]*\.[[:digit:]]*\.[[:digit:]]*\.[[:digit:]]*\).*/\1/g"`"
temp="`cat /sys/class/thermal/thermal_zone0/temp | cut -c1-2`"

echo $ip > /home/$user/.raspimonitor

 titolo="Normal Status"
if [ "$ip_old" != "$ip" ]; then
 titolo="New IP"
elif [[ "$temp" > "$tempmax" ]]; then
 titolo="Alarm Temperature"
fi
 echo -e  "IP: $ip \nTemp: $temp " | mutt -s "MonitorMail | $titolo" $dest
exit
